<!-- <!DOCTYPE html>
<html lang="en">
<head>
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css"> -->
    <!-- <link rel="stylesheet" href="<?= SCRIPTS ?> -->
    <!-- <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap-theme.min.css">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></script>
    <title>Edit profil</title>
</head>

<body>
    

<div id="editform">
	<form method="post" action="">
		<label for="txtRegPwd" class="compulsory">New Password: </label> <input type="password" name="txtRegPwd" id="txtRegPwd" onblur="checkPassword(this.value);" /> <span class="reginfo" id="lblPass1"></span>
		<label for="txtRegPwd2" class="compulsory">Re-enter password: </label> <input type="password" name="txtRegPwd2" id="txtRegPwd2" onblur="verifyPassword(this.value);" /> <span class="reginfo" id="lblPass2"></span>
		<label for="txtEmail" class="compulsory">E-mail address: </label> <input type="text" disabled="disabled" name="txtEmail" id="txtEmail" value="<?php echo $arr[0]['user_email']; ?>" onblur="checkEmail(this.value, 'lblEmail', false);" /> <span class="reginfo" id="lblEmail"></span>
		<label for="txtPhone">Phone Number: </label> <input type="text" name="txtPhone" id="txtPhone" value="<?php echo (strlen($arr[0]['user_phone']) > 1)?$arr[0]['user_phone']:""; ?>" onblur="checkPhone(this.value);" /> <span class="reginfo" id="lblPhone"></span>
		<label for="txtMsn">MSN: </label> <input type="text" name="txtMsn" id="txtMsn" value="<?php echo (strlen($arr[0]['user_msn']) > 1)?$arr[0]['user_msn']:""; ?>" onblur="checkEmail(this.value, 'lblMsn', true);" /> <span class="reginfo" id="lblMsn"></span>
		<label for="txtYahoo">Yahoo: </label> <input type="text" name="txtYahoo" id="txtYahoo" value="<?php echo (strlen($arr[0]['user_yahoo']) > 1)?$arr[0]['user_yahoo']:""; ?>" onblur="checkEmail(this.value, 'lblYahoo', true);" /> <span class="reginfo" id="lblYahoo"></span>
		<label for="txtGtalk">GTalk: </label> <input type="text" name="txtGtalk" id="txtGtalk" value="<?php echo (strlen($arr[0]['user_gtalk']) > 1)?$arr[0]['user_gtalk']:""; ?>" onblur="checkEmail(this.value, 'lblGtalk', true);" /> <span class="reginfo" id="lblGtalk"></span>
		<label for="selCountry">Country: </label> <input type="text" name="selCountry" id="selCountry" value="<?php echo (strlen($arr[0]['user_country']) > 1)?$arr[0]['user_country']:""; ?>" />
		<label for="txtSig">Signature</label>
		<textarea id="txtSig" name="txtSig" rows="6"><?php echo (strlen($arr[0]['sig']) > 1)?$arr[0]['sig']:""; ?></textarea>
		<label for="txtSig" style="margin-left: 165px;">*HTML Tags allowed: &lt;b&gt;, &lt;i&gt;</label>
		<input type="submit" name="sbtChange" id="sbtChange" value="Save Changes" /> -->
		<!--<label for="txtPhone">Phone Number: </label> <input type="text" name="txtPhone" id="txtPhone" onblur="checkPhone(this.value);" />-->
	<!-- </form>
</div>
</body>
</html> -->